import type { TravelVibe, PlaceType, TravelStyle, BudgetLevel } from "@/types";

export interface CatalogEntry {
  city: string;
  country: string;
  countryFlag: string;
  iataWro: string;
  iataBer: string | null;
  tags: TravelStyle[];
  vibes: TravelVibe[];
  placeTypes: PlaceType[];
  budgetLevel: BudgetLevel;
  coverImage: string;
  description: string;
  wroPrice: number;
  wroDurationMin: number;
  wroAirline: string;
  wroDep: string;
  wroArr: string;
  berPrice: number | null;
  berDurationMin: number | null;
  berAirline: string | null;
  berDep: string | null;
  berArr: string | null;
}

export const CATALOG: CatalogEntry[] = [
  // ── Istniejące 10 ─────────────────────────────────────────────────────────
  {
    city: "Lizbona", country: "Portugalia", countryFlag: "🇵🇹",
    iataWro: "LIS", iataBer: "LIS",
    tags: ["history", "architecture", "food", "beach"],
    vibes: ["chill", "social"], placeTypes: ["charming", "beach_sun"],
    budgetLevel: "low", coverImage: "🏛️",
    description: "Miasto tramwajów, pastéis de nata i niesamowitych widoków za grosze.",
    wroPrice: 390, wroDurationMin: 215, wroAirline: "Ryanair", wroDep: "06:10", wroArr: "09:45",
    berPrice: 210, berDurationMin: 210, berAirline: "easyJet", berDep: "07:30", berArr: "11:00",
  },
  {
    city: "Barcelona", country: "Hiszpania", countryFlag: "🇪🇸",
    iataWro: "BCN", iataBer: "BCN",
    tags: ["architecture", "beach", "food", "nightlife"],
    vibes: ["social", "intense"], placeTypes: ["big_city", "beach_sun"],
    budgetLevel: "medium", coverImage: "🏗️",
    description: "Gaudí, tapas, plaże i tętniące życiem Ramblas — klasyk z powodu.",
    wroPrice: 420, wroDurationMin: 195, wroAirline: "Wizz Air", wroDep: "05:55", wroArr: "08:30",
    berPrice: 190, berDurationMin: 185, berAirline: "Ryanair", berDep: "06:45", berArr: "09:10",
  },
  {
    city: "Ateny", country: "Grecja", countryFlag: "🇬🇷",
    iataWro: "ATH", iataBer: "ATH",
    tags: ["history", "architecture", "food"],
    vibes: ["intense", "chill"], placeTypes: ["big_city", "charming"],
    budgetLevel: "low", coverImage: "🏺",
    description: "Akropol, souvlaki za 3€ i klimat śródziemnomorski przez cały rok.",
    wroPrice: 360, wroDurationMin: 205, wroAirline: "Ryanair", wroDep: "06:20", wroArr: "09:45",
    berPrice: 170, berDurationMin: 195, berAirline: "easyJet", berDep: "07:10", berArr: "10:25",
  },
  {
    city: "Rzym", country: "Włochy", countryFlag: "🇮🇹",
    iataWro: "FCO", iataBer: "FCO",
    tags: ["history", "architecture", "food"],
    vibes: ["intense", "chill"], placeTypes: ["big_city", "charming"],
    budgetLevel: "medium", coverImage: "🏟️",
    description: "Koloseum, pizza al taglio i fontanny — wieczne miasto nie bez powodu.",
    wroPrice: 310, wroDurationMin: 150, wroAirline: "Ryanair", wroDep: "07:00", wroArr: "09:30",
    berPrice: 130, berDurationMin: 145, berAirline: "easyJet", berDep: "06:30", berArr: "08:55",
  },
  {
    city: "Porto", country: "Portugalia", countryFlag: "🇵🇹",
    iataWro: "OPO", iataBer: "OPO",
    tags: ["history", "food", "architecture", "nature"],
    vibes: ["chill", "social"], placeTypes: ["charming"],
    budgetLevel: "low", coverImage: "🍷",
    description: "Wino porto, azulejos, kuchnia i strome uliczki nad rzeką Douro.",
    wroPrice: 370, wroDurationMin: 210, wroAirline: "Ryanair", wroDep: "06:00", wroArr: "09:30",
    berPrice: 185, berDurationMin: 205, berAirline: "Wizz Air", berDep: "07:20", berArr: "10:45",
  },
  {
    city: "Madryt", country: "Hiszpania", countryFlag: "🇪🇸",
    iataWro: "MAD", iataBer: "MAD",
    tags: ["history", "food", "nightlife", "architecture"],
    vibes: ["social", "intense"], placeTypes: ["big_city"],
    budgetLevel: "medium", coverImage: "🎨",
    description: "Prado, churros z czekoladą, tapas bary i kultura do późna w nocy.",
    wroPrice: 440, wroDurationMin: 200, wroAirline: "Wizz Air", wroDep: "06:15", wroArr: "09:35",
    berPrice: 220, berDurationMin: 195, berAirline: "Ryanair", berDep: "05:55", berArr: "09:10",
  },
  {
    city: "Praga", country: "Czechy", countryFlag: "🇨🇿",
    iataWro: "PRG", iataBer: null,
    tags: ["history", "architecture", "nightlife", "food"],
    vibes: ["social", "chill"], placeTypes: ["charming"],
    budgetLevel: "low", coverImage: "🏰",
    description: "Złota Praha — jeden z najpiękniejszych starych miast Europy za ułamek ceny.",
    wroPrice: 180, wroDurationMin: 70, wroAirline: "Ryanair", wroDep: "07:30", wroArr: "08:40",
    berPrice: null, berDurationMin: null, berAirline: null, berDep: null, berArr: null,
  },
  {
    city: "Palma de Mallorca", country: "Hiszpania", countryFlag: "🇪🇸",
    iataWro: "PMI", iataBer: "PMI",
    tags: ["beach", "nature", "food"],
    vibes: ["chill", "social"], placeTypes: ["beach_sun"],
    budgetLevel: "medium", coverImage: "🏖️",
    description: "Turkusowe wody, skały i party na plaży — rajska wyspa w sercu Morza Śródziemnego.",
    wroPrice: 380, wroDurationMin: 170, wroAirline: "Ryanair", wroDep: "06:30", wroArr: "09:20",
    berPrice: 160, berDurationMin: 160, berAirline: "easyJet", berDep: "07:00", berArr: "09:40",
  },
  {
    city: "Dubrownik", country: "Chorwacja", countryFlag: "🇭🇷",
    iataWro: "DBV", iataBer: "DBV",
    tags: ["history", "beach", "architecture", "nature"],
    vibes: ["chill", "active"], placeTypes: ["beach_sun", "charming"],
    budgetLevel: "medium", coverImage: "🌊",
    description: "Perła Adriatyku — mury miejskie, Game of Thrones i krystaliczna woda.",
    wroPrice: 290, wroDurationMin: 115, wroAirline: "Ryanair", wroDep: "07:45", wroArr: "09:40",
    berPrice: 165, berDurationMin: 105, berAirline: "easyJet", berDep: "06:50", berArr: "08:35",
  },
  {
    city: "Teneryfa", country: "Hiszpania", countryFlag: "🇪🇸",
    iataWro: "TFS", iataBer: "TFS",
    tags: ["beach", "nature", "food"],
    vibes: ["chill", "active"], placeTypes: ["beach_sun"],
    budgetLevel: "medium", coverImage: "🌋",
    description: "Wulkan Teide, wieczne słońce i oceana do szaleństwa — idealne na reset.",
    wroPrice: 520, wroDurationMin: 290, wroAirline: "Wizz Air", wroDep: "05:30", wroArr: "10:00",
    berPrice: 310, berDurationMin: 275, berAirline: "Ryanair", berDep: "06:15", berArr: "10:30",
  },

  // ── Europa Środkowa / Wschodnia ───────────────────────────────────────────
  {
    city: "Budapeszt", country: "Węgry", countryFlag: "🇭🇺",
    iataWro: "BUD", iataBer: "BUD",
    tags: ["history", "architecture", "food", "nightlife"],
    vibes: ["social", "chill"], placeTypes: ["big_city", "charming"],
    budgetLevel: "low", coverImage: "🌉",
    description: "Łaźnie termalne, ruinpuby i niesamowita architektura — jedna z najtańszych stolic Europy.",
    wroPrice: 200, wroDurationMin: 90, wroAirline: "Ryanair", wroDep: "07:45", wroArr: "09:15",
    berPrice: 90, berDurationMin: 85, berAirline: "Wizz Air", berDep: "08:00", berArr: "09:25",
  },
  {
    city: "Wiedeń", country: "Austria", countryFlag: "🇦🇹",
    iataWro: "VIE", iataBer: "VIE",
    tags: ["history", "architecture", "food"],
    vibes: ["chill", "intense"], placeTypes: ["big_city", "charming"],
    budgetLevel: "medium", coverImage: "🎻",
    description: "Pałace, Sachertorte i muzyka klasyczna — cesarska elegancja w przystępnej cenie.",
    wroPrice: 230, wroDurationMin: 80, wroAirline: "Ryanair", wroDep: "08:00", wroArr: "09:20",
    berPrice: 100, berDurationMin: 75, berAirline: "easyJet", berDep: "07:45", berArr: "09:00",
  },
  {
    city: "Bratysława", country: "Słowacja", countryFlag: "🇸🇰",
    iataWro: "BTS", iataBer: null,
    tags: ["history", "architecture", "food"],
    vibes: ["chill", "social"], placeTypes: ["charming"],
    budgetLevel: "low", coverImage: "🏰",
    description: "Urocze stare miasto, zamek nad Dunajem i tańsze niż Praga czy Wiedeń.",
    wroPrice: 150, wroDurationMin: 75, wroAirline: "Ryanair", wroDep: "07:30", wroArr: "08:45",
    berPrice: null, berDurationMin: null, berAirline: null, berDep: null, berArr: null,
  },
  {
    city: "Sofia", country: "Bułgaria", countryFlag: "🇧🇬",
    iataWro: "SOF", iataBer: "SOF",
    tags: ["history", "architecture", "food"],
    vibes: ["chill", "intense"], placeTypes: ["big_city", "charming"],
    budgetLevel: "low", coverImage: "⛪",
    description: "Najtańsza stolica UE — bałkańska kuchnia, kościoły i hipsterscy kawiarnie za grosze.",
    wroPrice: 260, wroDurationMin: 140, wroAirline: "Ryanair", wroDep: "06:30", wroArr: "09:10",
    berPrice: 140, berDurationMin: 135, berAirline: "Wizz Air", berDep: "07:00", berArr: "09:15",
  },
  {
    city: "Belgrad", country: "Serbia", countryFlag: "🇷🇸",
    iataWro: "BEG", iataBer: "BEG",
    tags: ["nightlife", "food", "history"],
    vibes: ["social", "intense"], placeTypes: ["big_city"],
    budgetLevel: "low", coverImage: "🎶",
    description: "Legendarny nightlife, spit-roast mięso i Twierdza Kalemegdan — Bałkany w pigułce.",
    wroPrice: 250, wroDurationMin: 120, wroAirline: "Wizz Air", wroDep: "07:00", wroArr: "09:00",
    berPrice: 130, berDurationMin: 115, berAirline: "Ryanair", berDep: "07:30", berArr: "09:25",
  },
  {
    city: "Wilno", country: "Litwa", countryFlag: "🇱🇹",
    iataWro: "VNO", iataBer: null,
    tags: ["history", "architecture", "food"],
    vibes: ["chill", "social"], placeTypes: ["charming"],
    budgetLevel: "low", coverImage: "🕍",
    description: "Barokowe stare miasto UNESCO, street art i kawiarnie — perełka Bałtyku.",
    wroPrice: 170, wroDurationMin: 80, wroAirline: "Ryanair", wroDep: "07:30", wroArr: "08:50",
    berPrice: null, berDurationMin: null, berAirline: null, berDep: null, berArr: null,
  },
  {
    city: "Ryga", country: "Łotwa", countryFlag: "🇱🇻",
    iataWro: "RIX", iataBer: null,
    tags: ["history", "architecture", "nightlife"],
    vibes: ["social", "chill"], placeTypes: ["charming", "big_city"],
    budgetLevel: "low", coverImage: "🏘️",
    description: "Jugendstil na każdym kroku, targ Centralny i nocne życie nad Dźwiną.",
    wroPrice: 190, wroDurationMin: 90, wroAirline: "Ryanair", wroDep: "07:30", wroArr: "09:00",
    berPrice: null, berDurationMin: null, berAirline: null, berDep: null, berArr: null,
  },
  {
    city: "Tallin", country: "Estonia", countryFlag: "🇪🇪",
    iataWro: "TLL", iataBer: "TLL",
    tags: ["history", "architecture", "food"],
    vibes: ["chill", "social"], placeTypes: ["charming"],
    budgetLevel: "low", coverImage: "🏯",
    description: "Najlepiej zachowane średniowieczne stare miasto Europy — bajka z kamienia.",
    wroPrice: 230, wroDurationMin: 115, wroAirline: "Ryanair", wroDep: "06:45", wroArr: "08:40",
    berPrice: 110, berDurationMin: 110, berAirline: "easyJet", berDep: "07:15", berArr: "09:05",
  },

  // ── Włochy ────────────────────────────────────────────────────────────────
  {
    city: "Mediolan", country: "Włochy", countryFlag: "🇮🇹",
    iataWro: "MXP", iataBer: "MXP",
    tags: ["food", "architecture", "nightlife"],
    vibes: ["intense", "social"], placeTypes: ["big_city"],
    budgetLevel: "medium", coverImage: "👗",
    description: "Moda, design, spritz i Da Vinci — kulturalna stolica Włoch.",
    wroPrice: 290, wroDurationMin: 130, wroAirline: "Ryanair", wroDep: "06:30", wroArr: "08:40",
    berPrice: 140, berDurationMin: 125, berAirline: "easyJet", berDep: "07:00", berArr: "09:05",
  },
  {
    city: "Florencja", country: "Włochy", countryFlag: "🇮🇹",
    iataWro: "FLR", iataBer: "FLR",
    tags: ["history", "architecture", "food"],
    vibes: ["intense", "chill"], placeTypes: ["charming", "big_city"],
    budgetLevel: "medium", coverImage: "🎭",
    description: "Uffizi, Dawid i bistecca alla Fiorentina — renesans na każdym rogu.",
    wroPrice: 320, wroDurationMin: 130, wroAirline: "Ryanair", wroDep: "07:00", wroArr: "09:10",
    berPrice: 160, berDurationMin: 125, berAirline: "Ryanair", berDep: "07:15", berArr: "09:20",
  },
  {
    city: "Wenecja", country: "Włochy", countryFlag: "🇮🇹",
    iataWro: "VCE", iataBer: "VCE",
    tags: ["history", "architecture"],
    vibes: ["chill", "intense"], placeTypes: ["charming"],
    budgetLevel: "medium", coverImage: "🚤",
    description: "Kanały, gondole i labiryntowe uliczki — miasto jak sen, zanim zatonie.",
    wroPrice: 280, wroDurationMin: 120, wroAirline: "Ryanair", wroDep: "07:15", wroArr: "09:15",
    berPrice: 140, berDurationMin: 115, berAirline: "easyJet", berDep: "07:30", berArr: "09:25",
  },
  {
    city: "Neapol", country: "Włochy", countryFlag: "🇮🇹",
    iataWro: "NAP", iataBer: "NAP",
    tags: ["history", "food", "architecture"],
    vibes: ["intense", "chill"], placeTypes: ["big_city", "charming"],
    budgetLevel: "low", coverImage: "🍕",
    description: "Kolebka pizzy, Pompeje i Wezuwiusz — południe Włoch bez filtra.",
    wroPrice: 310, wroDurationMin: 155, wroAirline: "Ryanair", wroDep: "06:15", wroArr: "09:10",
    berPrice: 160, berDurationMin: 150, berAirline: "Wizz Air", berDep: "06:45", berArr: "09:15",
  },
  {
    city: "Katania", country: "Włochy", countryFlag: "🇮🇹",
    iataWro: "CTA", iataBer: "CTA",
    tags: ["history", "food", "nature"],
    vibes: ["chill", "active"], placeTypes: ["charming"],
    budgetLevel: "low", coverImage: "🌋",
    description: "Sycylia u stóp Etny — arancini, bazalt i barokowe pałace za bezcen.",
    wroPrice: 330, wroDurationMin: 170, wroAirline: "Ryanair", wroDep: "06:00", wroArr: "08:50",
    berPrice: 170, berDurationMin: 165, berAirline: "Ryanair", berDep: "06:20", berArr: "09:05",
  },

  // ── Grecja ────────────────────────────────────────────────────────────────
  {
    city: "Saloniki", country: "Grecja", countryFlag: "🇬🇷",
    iataWro: "SKG", iataBer: "SKG",
    tags: ["history", "food", "nightlife"],
    vibes: ["social", "chill"], placeTypes: ["big_city", "charming"],
    budgetLevel: "low", coverImage: "🏛️",
    description: "Drugie miasto Grecji — uliczna kuchnia, bary do świtu i Rotonda z III wieku.",
    wroPrice: 300, wroDurationMin: 165, wroAirline: "Ryanair", wroDep: "06:00", wroArr: "08:45",
    berPrice: 150, berDurationMin: 160, berAirline: "easyJet", berDep: "06:30", berArr: "09:10",
  },
  {
    city: "Heraklion", country: "Grecja", countryFlag: "🇬🇷",
    iataWro: "HER", iataBer: "HER",
    tags: ["history", "beach", "nature"],
    vibes: ["chill", "active"], placeTypes: ["beach_sun"],
    budgetLevel: "low", coverImage: "🏺",
    description: "Kreta — pałac Knossos, Samaria i plaże Elafonisi w jednym.",
    wroPrice: 380, wroDurationMin: 195, wroAirline: "Ryanair", wroDep: "05:55", wroArr: "09:10",
    berPrice: 200, berDurationMin: 190, berAirline: "easyJet", berDep: "06:15", berArr: "09:25",
  },
  {
    city: "Korfu", country: "Grecja", countryFlag: "🇬🇷",
    iataWro: "CFU", iataBer: "CFU",
    tags: ["beach", "nature", "history"],
    vibes: ["chill", "active"], placeTypes: ["beach_sun"],
    budgetLevel: "medium", coverImage: "🌿",
    description: "Venetian Stare Miasto, oliwkowe gaje i turkusowe plaże — wenecja Jonii.",
    wroPrice: 360, wroDurationMin: 175, wroAirline: "Ryanair", wroDep: "06:10", wroArr: "09:05",
    berPrice: 190, berDurationMin: 170, berAirline: "Wizz Air", berDep: "06:40", berArr: "09:30",
  },
  {
    city: "Rodos", country: "Grecja", countryFlag: "🇬🇷",
    iataWro: "RHO", iataBer: "RHO",
    tags: ["beach", "history", "nature"],
    vibes: ["chill", "active"], placeTypes: ["beach_sun"],
    budgetLevel: "medium", coverImage: "🦌",
    description: "Średniowieczne miasto rycerzy, krystaliczne wody i całoroczne słońce.",
    wroPrice: 400, wroDurationMin: 195, wroAirline: "Wizz Air", wroDep: "05:50", wroArr: "09:05",
    berPrice: 220, berDurationMin: 190, berAirline: "easyJet", berDep: "06:10", berArr: "09:20",
  },

  // ── Chorwacja / Adriatyk ──────────────────────────────────────────────────
  {
    city: "Split", country: "Chorwacja", countryFlag: "🇭🇷",
    iataWro: "SPU", iataBer: "SPU",
    tags: ["beach", "history", "nature"],
    vibes: ["chill", "active"], placeTypes: ["beach_sun", "charming"],
    budgetLevel: "low", coverImage: "⛵",
    description: "Dioklecjanowy pałac zamieniony w żywe miasto — wyspy, trasy i Adriatyk.",
    wroPrice: 250, wroDurationMin: 110, wroAirline: "Ryanair", wroDep: "07:30", wroArr: "09:20",
    berPrice: 120, berDurationMin: 105, berAirline: "Ryanair", berDep: "07:50", berArr: "09:35",
  },
  {
    city: "Zadar", country: "Chorwacja", countryFlag: "🇭🇷",
    iataWro: "ZAD", iataBer: "ZAD",
    tags: ["beach", "history", "nature"],
    vibes: ["chill", "active"], placeTypes: ["beach_sun", "charming"],
    budgetLevel: "low", coverImage: "🌅",
    description: "Organy morskie, Sea Organ i parki narodowe — mniej tłoczna alternatywa dla Splitu.",
    wroPrice: 240, wroDurationMin: 100, wroAirline: "Ryanair", wroDep: "07:45", wroArr: "09:25",
    berPrice: 110, berDurationMin: 95, berAirline: "Wizz Air", berDep: "08:00", berArr: "09:35",
  },

  // ── Hiszpania (kontynentalna i wyspy) ─────────────────────────────────────
  {
    city: "Walencja", country: "Hiszpania", countryFlag: "🇪🇸",
    iataWro: "VLC", iataBer: "VLC",
    tags: ["beach", "food", "architecture"],
    vibes: ["chill", "social"], placeTypes: ["big_city", "beach_sun"],
    budgetLevel: "low", coverImage: "🥘",
    description: "Ojczyzna paelli, futurystyczne miasto sztuki i plaże bez tłumów Barcelony.",
    wroPrice: 340, wroDurationMin: 185, wroAirline: "Ryanair", wroDep: "06:05", wroArr: "09:10",
    berPrice: 180, berDurationMin: 180, berAirline: "Ryanair", berDep: "06:30", berArr: "09:30",
  },
  {
    city: "Alicante", country: "Hiszpania", countryFlag: "🇪🇸",
    iataWro: "ALC", iataBer: "ALC",
    tags: ["beach", "nature", "food"],
    vibes: ["chill", "active"], placeTypes: ["beach_sun"],
    budgetLevel: "low", coverImage: "🏰",
    description: "Zamek Santa Bárbara, promenada i tanie loty — brama do Costy Blanca.",
    wroPrice: 320, wroDurationMin: 175, wroAirline: "Ryanair", wroDep: "06:15", wroArr: "09:10",
    berPrice: 170, berDurationMin: 170, berAirline: "easyJet", berDep: "06:40", berArr: "09:30",
  },
  {
    city: "Malaga", country: "Hiszpania", countryFlag: "🇪🇸",
    iataWro: "AGP", iataBer: "AGP",
    tags: ["beach", "food", "history"],
    vibes: ["chill", "social"], placeTypes: ["beach_sun", "charming"],
    budgetLevel: "low", coverImage: "🌞",
    description: "Picasso, tapas i Costa del Sol — andaluzyjskie słońce przez cały rok.",
    wroPrice: 350, wroDurationMin: 185, wroAirline: "Ryanair", wroDep: "06:10", wroArr: "09:15",
    berPrice: 190, berDurationMin: 180, berAirline: "easyJet", berDep: "06:30", berArr: "09:30",
  },
  {
    city: "Sewilla", country: "Hiszpania", countryFlag: "🇪🇸",
    iataWro: "SVQ", iataBer: "SVQ",
    tags: ["history", "architecture", "food"],
    vibes: ["intense", "chill"], placeTypes: ["big_city", "charming"],
    budgetLevel: "low", coverImage: "💃",
    description: "Flamenco, Alcázar i najlepsza tapas kultura Andaluzji — magia południa.",
    wroPrice: 370, wroDurationMin: 195, wroAirline: "Ryanair", wroDep: "05:55", wroArr: "09:10",
    berPrice: 200, berDurationMin: 190, berAirline: "Ryanair", berDep: "06:15", berArr: "09:25",
  },
  {
    city: "Ibiza", country: "Hiszpania", countryFlag: "🇪🇸",
    iataWro: "IBZ", iataBer: "IBZ",
    tags: ["beach", "nightlife", "food"],
    vibes: ["social", "chill"], placeTypes: ["beach_sun"],
    budgetLevel: "medium", coverImage: "🎧",
    description: "Plaże za dnia, najsłynniejsze kluby świata w nocy — White Isle nie śpi.",
    wroPrice: 360, wroDurationMin: 185, wroAirline: "Ryanair", wroDep: "06:05", wroArr: "09:10",
    berPrice: 190, berDurationMin: 180, berAirline: "easyJet", berDep: "06:25", berArr: "09:25",
  },
  {
    city: "Fuerteventura", country: "Hiszpania", countryFlag: "🇪🇸",
    iataWro: "FUE", iataBer: "FUE",
    tags: ["beach", "nature"],
    vibes: ["chill", "active"], placeTypes: ["beach_sun"],
    budgetLevel: "medium", coverImage: "🏄",
    description: "Białe wydmy, kite-surfing i wieczne słońce — hawajskie klimaty bliżej niż myślisz.",
    wroPrice: 490, wroDurationMin: 295, wroAirline: "Ryanair", wroDep: "05:30", wroArr: "10:25",
    berPrice: 230, berDurationMin: 290, berAirline: "Ryanair", berDep: "05:50", berArr: "10:40",
  },

  // ── Portugalia ────────────────────────────────────────────────────────────
  {
    city: "Faro", country: "Portugalia", countryFlag: "🇵🇹",
    iataWro: "FAO", iataBer: "FAO",
    tags: ["beach", "nature", "food"],
    vibes: ["chill", "active"], placeTypes: ["beach_sun"],
    budgetLevel: "low", coverImage: "🐚",
    description: "Brama do Algarve — klify, złote plaże i owoce morza prosto z kutra.",
    wroPrice: 380, wroDurationMin: 215, wroAirline: "Ryanair", wroDep: "05:50", wroArr: "09:25",
    berPrice: 210, berDurationMin: 210, berAirline: "easyJet", berDep: "06:10", berArr: "09:40",
  },
  {
    city: "Funchal", country: "Portugalia (Madera)", countryFlag: "🇵🇹",
    iataWro: "FNC", iataBer: "FNC",
    tags: ["nature", "beach", "food"],
    vibes: ["chill", "active"], placeTypes: ["beach_sun", "charming"],
    budgetLevel: "medium", coverImage: "🌺",
    description: "Kwiatonośna wyspa na Atlantyku — tobogany, poncha i klify Cabo Girão.",
    wroPrice: 500, wroDurationMin: 290, wroAirline: "Ryanair", wroDep: "05:35", wroArr: "10:25",
    berPrice: 310, berDurationMin: 285, berAirline: "Ryanair", berDep: "05:55", berArr: "10:40",
  },

  // ── Francja / Riwiera ─────────────────────────────────────────────────────
  {
    city: "Paryż", country: "Francja", countryFlag: "🇫🇷",
    iataWro: "CDG", iataBer: "CDG",
    tags: ["history", "architecture", "food"],
    vibes: ["intense", "chill"], placeTypes: ["big_city", "charming"],
    budgetLevel: "medium", coverImage: "🗼",
    description: "Wieża Eiffla, croissanty i muzea za free w niedzielę — miasto miłości i kultury.",
    wroPrice: 320, wroDurationMin: 165, wroAirline: "Ryanair", wroDep: "06:00", wroArr: "08:45",
    berPrice: 150, berDurationMin: 160, berAirline: "easyJet", berDep: "06:20", berArr: "09:00",
  },
  {
    city: "Nicea", country: "Francja", countryFlag: "🇫🇷",
    iataWro: "NCE", iataBer: "NCE",
    tags: ["beach", "food", "architecture"],
    vibes: ["chill", "social"], placeTypes: ["beach_sun", "charming"],
    budgetLevel: "medium", coverImage: "🌊",
    description: "Lazurowe Wybrzeże — promenada Anglais, socca i widok na Monaco.",
    wroPrice: 310, wroDurationMin: 165, wroAirline: "easyJet", wroDep: "06:20", wroArr: "09:05",
    berPrice: 160, berDurationMin: 160, berAirline: "easyJet", berDep: "06:40", berArr: "09:20",
  },

  // ── Benelux / Północ ──────────────────────────────────────────────────────
  {
    city: "Amsterdam", country: "Holandia", countryFlag: "🇳🇱",
    iataWro: "AMS", iataBer: "AMS",
    tags: ["history", "architecture", "food", "nightlife"],
    vibes: ["social", "chill"], placeTypes: ["big_city", "charming"],
    budgetLevel: "medium", coverImage: "🚲",
    description: "Kanały, van Gogh, tulipany i kawiarnie — jeden z najbardziej rowerowych miast świata.",
    wroPrice: 280, wroDurationMin: 130, wroAirline: "Ryanair", wroDep: "06:30", wroArr: "08:40",
    berPrice: 110, berDurationMin: 125, berAirline: "easyJet", berDep: "06:50", berArr: "08:55",
  },
  {
    city: "Kopenhaga", country: "Dania", countryFlag: "🇩🇰",
    iataWro: "CPH", iataBer: "CPH",
    tags: ["history", "food", "architecture"],
    vibes: ["chill", "social"], placeTypes: ["big_city", "charming"],
    budgetLevel: "medium", coverImage: "🧜",
    description: "Hygge, Noma i kolorowe domy nad kanałem — nordycki styl życia w pełnej krasie.",
    wroPrice: 340, wroDurationMin: 150, wroAirline: "Ryanair", wroDep: "06:15", wroArr: "08:45",
    berPrice: 130, berDurationMin: 145, berAirline: "Ryanair", berDep: "06:35", berArr: "09:00",
  },

  // ── Wyspy Brytyjskie ──────────────────────────────────────────────────────
  {
    city: "Edynburg", country: "Szkocja", countryFlag: "🏴󠁧󠁢󠁳󠁣󠁴󠁿",
    iataWro: "EDI", iataBer: "EDI",
    tags: ["history", "architecture", "nature"],
    vibes: ["chill", "active"], placeTypes: ["charming"],
    budgetLevel: "medium", coverImage: "🏰",
    description: "Zamek na wulkanicznej skale, whisky i festiwal Fringe — szkocka dusza w kamieniu.",
    wroPrice: 370, wroDurationMin: 170, wroAirline: "Ryanair", wroDep: "06:00", wroArr: "08:50",
    berPrice: 180, berDurationMin: 165, berAirline: "easyJet", berDep: "06:20", berArr: "09:05",
  },
  {
    city: "Dublin", country: "Irlandia", countryFlag: "🇮🇪",
    iataWro: "DUB", iataBer: "DUB",
    tags: ["nightlife", "food", "history"],
    vibes: ["social", "chill"], placeTypes: ["big_city", "charming"],
    budgetLevel: "medium", coverImage: "🍺",
    description: "Puby Temple Bar, klify Howth i ciepłe dusze Irlandczyków — piwo Guinness smakuje tu inaczej.",
    wroPrice: 390, wroDurationMin: 195, wroAirline: "Ryanair", wroDep: "05:50", wroArr: "09:05",
    berPrice: 200, berDurationMin: 190, berAirline: "Ryanair", berDep: "06:10", berArr: "09:20",
  },
];
